# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'microsoft'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean
      run: dotnet clean

    - name: Restore dependencies
      run: dotnet restore

    - name: Install ANTLR
      run: |
        wget https://www.antlr.org/download/antlr-4.13.2-complete.jar

    - name: Generate code using ANTLR
      run: |
        java -jar "antlr-4.13.2-complete.jar" -Dlanguage=CSharp -package System.RelativeTime.Compiler -visitor "./System.Extensions/System/RelativeTime/Compiler/Expression.g4"

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
